### ISSUE TITLE
Segregate Cross-Cutting-Concerns and don't break layers

### ISSUE THREAD

**Issue by mamuz** [ATDDWorkshop/shop#3]
https://github.com/ATDDWorkshop/shop/blob/master/module/Shop/src/Shop/Controller/ShopController.php
- Checking User Login (cross cutting concern) have to be segregated to a listener and attach this to application to avoid duplicated code.
- Segregate domain logic to an own layer: fetch and buy in `buyAction`

**Comment by gregormey** [comment]
decided to keep it like it is
